### ISSUE TITLE
sponcership

### ISSUE THREAD

**Issue by honeyakshat999** [hackclub/hackathons#11]
Hello,
Greetings from Team Code N Run!
 
We take the honor to announce the Code N Run getting hosted at The Amity University Rajasthan, Jaipur, from 28th february 2019 12 am to 29th February 2019 at 1 pm in its techno-cultural fest ODYSSEY'2020. 
 
We are writing to you concerning a sponsorship opportunity with Code N Run. 
 
Code N Run is a 24-hour long event with a vision to provide hands-on experience in the field of Technologies and Ideas. It's a 24-hours event where developers come together to share ideas, make teams, build projects, and show their creativity!
 
A Codeathon is a design sprint-like event, in which computer programmers and others involved in software development, including graphic designers, interface designers, project managers, domain experts, and others collaborate intensively on software projects.

Here is what happens at Code n Run:
1: Meet, Pitch and Team Up
2: Learn & Work
3: Present and Celebrate
You are our first reach as a monetary sponsor and we hope for a positive response. If your organization would like to participate in this year’s event as a sponsor, please contact us. Thank you for your time and consideration, and we look forward to hearing from you
Sincerely,
Team Code n Run

**Comment by zachlatta** [comment]
Hey, can you email us at team@hackclub.com? We can put you in touch with @athul-blesson who leads Hack Club in India.

This GitHub repo isn't the right place for requests like these.
