### ISSUE TITLE
Events out of order

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hackathons#16]
<img width="1559" alt="Screenshot 2020-04-23 18 18 26" src="https://user-images.githubusercontent.com/5891442/80155083-e8742f00-858e-11ea-8bd6-78e4d2ccba98.png">

**Comment by lachlanjc** [comment]
This should be an easy fix—add a line like https://github.com/hackclub/events/blob/master/lib/data.js#L26 right here: https://github.com/hackclub/hackathons/blob/master/lib/data.js#L38
