### ISSUE TITLE
Date issues for hackathons that start and stop in different months

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hackathons#17]
<img width="699" alt="Screenshot 2020-04-28 21 58 55" src="https://user-images.githubusercontent.com/5891442/80554541-85720600-899b-11ea-898c-04d7c5dd1dd4.png">

<img width="504" alt="Screenshot 2020-04-28 21 57 59" src="https://user-images.githubusercontent.com/5891442/80554550-8c007d80-899b-11ea-8a93-b19dccd8b8aa.png">

**Comment by maxwofford** [comment]
huh, think #20 accidentally fixed this. oh well :shrug:

**Comment by lachlanjc** [comment]
Stunning
