### ISSUE TITLE
Fix date display for events starting on the first of the month

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hackathons#18]
<img width="522" alt="Screenshot 2020-04-28 22 03 37" src="https://user-images.githubusercontent.com/5891442/80554763-2b257500-899c-11ea-9dd0-4b56d4cd7879.png">
<img width="512" alt="Screenshot 2020-04-28 22 03 32" src="https://user-images.githubusercontent.com/5891442/80554765-2bbe0b80-899c-11ea-914a-bb481a2cf470.png">

**Comment by lachlanjc** [comment]
We’re having this issue on 2 events right now, MakeSPP & DistanceHacks. I *suspect* that timezones are biting us somehow—had the same issue on Events, but haven’t fully investigated.
