### ISSUE TITLE
Low contrast on CTA for Hackathon Organizers

### ISSUE THREAD

**Issue by garyhtou** [hackclub/hackathons#303]
In dark mode, the title in the call to action card for Hackathon Organizers has low contrast against the card's background.

![image](https://github.com/hackclub/hackathons/assets/20099646/18410c75-e74a-4079-ab46-e2c8b8e00433)

I'd suggest keeping `"Organizing a hackathon? Hack Club is here to help."` always black regardless of light/dark mode. (the card's background doesn't change colors when toggling light/dark mode)

**Comment by FahadLive** [comment]
I have opened a pull request with the quick fix for this issue

**Comment by FahadLive** [comment]
@garyhtou @sampoder The issue can be closed now. Right?

**Comment by garyhtou** [comment]
Yes! ty
