### ISSUE TITLE
Add Contributing.md for the repo

### ISSUE THREAD

**Issue by nimit2801** [hackclub/hackathons#37]
I would like to make one for this repo.
If there are few things that I've to add specifically, can you please inform me in the comment section?
Thank You.

**Comment by nimit2801** [comment]
I would like to make one for this repo.
If there are few things that I've to add specifically, can you please inform me in the comment section?
Thank You.

**Comment by sampoder** [comment]
There's kind of already a contributing doc in the README that you could use as a base

**Comment by nimit2801** [comment]
I hope @sampoder this contributing.md would help newcomers a lot, and make this repo more friendly.

**Comment by johnbabu021** [comment]
first, everyone looks at the readme if they don't find that then only look back to contribute.md
