### ISSUE TITLE
Email Sign-up form Errors

### ISSUE THREAD

**Issue by exu3** [hackclub/hackathons#79]
When I submit the email signup form, I get a success message on the page, but there is a console error, and I don't seem to receive an email

https://github.com/hackclub/api/blob/master/app/controllers/v1/event_email_subscribers_controller.rb seems to be the API endpoint for the email sign up

<img width="1268" alt="Screen Shot 2021-11-06 at 1 11 50 AM" src="https://user-images.githubusercontent.com/72365100/140602939-aa1dfa8b-0cb4-4dab-89db-c45a5291d02a.png">

**Comment by sampoder** [comment]
This shouldn't matter:

```
    try {
      window.analytics.identify({ email })
      window.analytics.track('Submitted Email', { email, location })
    } catch (err) {
      console.error(err)
    }
```

**Comment by sampoder** [comment]
Can confirm it works, closing for now

<img width="950" alt="Screenshot 2021-11-06 at 4 50 52 PM" src="https://user-images.githubusercontent.com/39828164/140603900-b4e3ef85-0306-4108-add2-f0cb6a98eee3.png">
