### ISSUE TITLE
Chrome autofill text color

### ISSUE THREAD

**Issue by exu3** [hackclub/hackathons#80]
![Screenshot_20211106-020531.png](https://user-images.githubusercontent.com/72365100/140604439-9f9f1c5e-945e-4da4-a77b-e619f9474ec6.png)

The text color for chrome autofill is black which doesn't work well in dark mode

**Comment by sampoder** [comment]
Could you provide some more reproduction details?

![Screenshot_20211106-173441_Chrome.jpg](https://user-images.githubusercontent.com/39828164/140605119-977d2a7e-73c6-4f85-8ed4-d2295cedec81.jpg)

**Comment by exu3** [comment]
When you have saved passwords/emails/names/etc in the browser, [chrome autofills it for you](https://support.google.com/chrome/answer/142893?hl=en&co=GENIE.Platform%3DAndroid) on certain sites. The default autofill text style on Chrome is just black text color. This is the issue in question with the input fields on the hackathons site. 

For example, Safari's default autofill text color is blue bg and white or black text depending on the page theme
<img width="915" alt="Screen Shot 2021-11-06 at 9 31 01 AM" src="https://user-images.githubusercontent.com/72365100/140616844-13e715f4-ec9d-4d11-b184-0e3dcec51740.png">

I could make a PR to fix this today

**Comment by sampoder** [comment]
Ooo.... interesting TIL! I've never seen that before wow...A PR would be
wonderful, thank you. I'm curious to see the fix
